# name of the workflow
name: Build & Deploy Spring app

# specifying when to trigger these actions
on:
  # we want to trigger the pipeline on push
  push:
    branches: # we specify the branches
      - main

jobs:
  # This is the main job, which we called build-deploy
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    # defining a runner (see notion for explanation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # we are not going to run an action, because only need to run a command
      - name: Unit Tests
        # we have only one command, we can just pass it as parameter
        run: mvn -B test --file pom.xml

      - name: Build the application
        # in case we have multiple commands, we do like so:
        run: |
          mvn clean
          mvn -B package --file pom.xml